version: "3"

tasks:
  migration:
    aliases:
      - mig
    desc: "Migrate db"
    cmds:
      - go run ./internal/lib/migrator --storage-path=./storage/sso.db --migration-path=./config/migrations
  initDocker:
    aliases:
      - docker
    desc: "Create docker image"

