# config.yaml для message-сервиса (работает на порту 44045)
env: "local"
app_secret: "secret"

storage:
  path: "./message/storage/messages.db"  # Отдельное хранилище для сообщений

grpc:
  server:
    port: 44045  # Порт, на котором работает message-сервис
    timeout: 1h   # Таймаут для серверных операций

clients:
  crud:
    addr: "localhost:44045"  # Для внутреннего использования (сам себя)
    timeout: 3s
    retries_count: 3